### ISSUE TITLE
How to run 'ML_backdoor.py'

### ISSUE THREAD

**Issue by DemoAllan** [DistributedML/FoolsGold#1]
Excuse me, sir. I wonder how to run the file 'ML_backdoor.py'? It seems like it doesn't run as 'ML_main.py'. Thank you for your anwsering.

**Comment by bestchai** [comment]
The code is the documentation for this file. At the bottom of the file you'll see:
```
if __name__ == "__main__":
    argv = sys.argv[1:]

    dataset = argv[0]
    iterations = int(argv[1])

    if (dataset == "mnist"):
        numClasses = 10
        numFeatures = 784
    elif (dataset == "kddcup"):
        numClasses = 23
        numFeatures = 41
    elif (dataset == "amazon"):
        numClasses = 50
        numFeatures = 10000
    else:
        print("Dataset " + dataset + " not found. Available datasets: mnist kddcup amazon")
```

This captures the proper args you should use when running this file from the command line i.e., as "python ML_backdoor.py [ARG1] [ARG2]"

**Comment by clementfung** [comment]
@DemoAllan An alternate (and probably more up to date) method would be to use ML_main.py, but use the label 'b' for the source label. So, instead of 5_1_7, use 5_b_7.

You'll also need to run misslabel_dataset.py to generate backdoored data.
See: https://github.com/DistributedML/FoolsGold/blob/master/ML/code/misslabel_dataset.py#L15
