### ISSUE TITLE
Getting warnings when running the example and errors when running various tests

### ISSUE THREAD

**Issue by AlexWink** [DistributedML/FoolsGold#5]
Hello,
When I run the example in the README.md, I get the warning 
"FoolsGold/ML/code/model_aggregator.py:116: RuntimeWarning: divide by zero encountered in log
  wv = (np.log(wv / (1 - wv)) + 0.5)" numerous times.
I also tried to run other examples but it turned out the xrange() function is sometimes called and it exists only in python2 which cant run the project because of the used libraries.

**Comment by clementfung** [comment]
Hi Alex,

Thanks for your issue! I just pushed a fix that adds a small epsilon value to the required lines in the FoolsGold algorithm, which should stop the warnings from occurring.

Regarding the Python2 vs Python3 issue, this is something I've been putting off for a bit too long. Since this is a separate change that is a bit bigger, I've opened a separate issue to track Python 3 at #6
